### ISSUE TITLE
Trouble running in windows 7

### ISSUE THREAD

**Issue by rshum19** [fagg/matlab-zmq#31]
Hello, 

I'm trying to get it matlab-zmq to work on my Windows 7 x64 machine. I have installed ZMQ using the windows installer (http://zeromq.org/distro:microsoft-windows). I'm running Matlab R2013a and have set my to "Microsoft Windows SDK 7.1". I set the config.m file as indicated and run make. 

I get a successful build:

Succesful build for:
	ZMQ_INCLUDE_PATH = C:\Program Files\ZeroMQ 4.0.4\include
	ZMQ_LIB_PATH = C:\Program Files\ZeroMQ 4.0.4\lib\
	ZMQ_COMPILED_LIB = libzmq-v100-mt-4_0_4.lib

ans =

     1

However, is I run make('test') all the test fail. Further, if I run one of the examples it gives me the following error:

Invalid MEX-file 'C:\Users\<user-name>\Downloads\matlab-zmq-dev\matlab-zmq-dev\lib\+zmq\+core\ctx_new.mexw64': The
specified module could not be found.

Error in pub_server (line 16)
    context = zmq.core.ctx_new();

Any insight in why this is happening??

Thanks

**Comment by fagg** [comment]
Which branch are you using? Please try master if you're using dev.

**Comment by rshum19** [comment]
I've tried both branches and both seem to give me the same mistake. I have the impression that it has to be the installation of ZeroMQ. I don't know if you have any recommendations/indications on hot to install ZeroMQ in windows?  

I usually work on linux but for this specific project I need it to be on windows. I used your binding in linux before with no trouble.

**Comment by fagg** [comment]
I lack the equipment to test with Windows, however if I had to hazard a guess I would suggest it is not linking to ZMQ correctly. 

Other people have had success in getting it working with Windows, and as far as I know the default suggestions from ZMQ are fine for our purposes. I'm sorry I can't be of more help. 

However, looking at the error message you provided, can you please check the .mexw64 file it references actually exists on that path? The path looks weird. 

Also what happens if you just make sure the lib directory is on your path and call context = zmq.core.ctx_new()?

**Comment by rshum19** [comment]
I found the issue. Removing the  '\' at the end of my library path. It apparently the '\' would point to some location and prevent matlab from finding the library. 

% ZMQ library path
ZMQ_LIB_PATH = 'C:\Program Files\ZeroMQ 4.0.4\lib'; 

instead of 

% ZMQ library path
ZMQ_LIB_PATH = 'C:\Program Files\ZeroMQ 4.0.4\lib\';

**Comment by fagg** [comment]
This is very strange.

I recently took a commit from someone else who removed the trailing \ at the end of the include path definition to fix compiling on Windows. Strangely, the trailing \ on ZMQ_LIB_PATH does not seem to cause issues for them (I assume).

This needs to be addressed differently, I feel.

I appreciate the feedback. Thanks.

Ash

**Comment by Fetz93** [comment]
Hello,

i have the same problem. I can run the make file and everything is compiled fine. But when I run make test, then every test fails and says invalid mex file...
The solution of removing the slash doesn't work with me. I also tried it on several PCs, but the error remains the same.
I use Windows 7 x64 and tried it with Matlab 2016a and 2012b. For the compiler I tried Windows SDK 7.1 and Visual Studio 2013. Also tried master and dev branch.

Any help is appreciated, thanks!

**Comment by abravalheri** [comment]
Hello @Fetz93,

Maybe this is a problem with the compatibility between the ZeroMQ binaries and the compiler used for MATLAB. Could you please send the logs, the configuration in `config_win.m`, and the output from the following command?

``` matlab
mex.getCompilerConfigurations('C','Selected')
```

**Comment by Fetz93** [comment]
Hello @abravalheri 

thank you for your reply. Here are the log files:
[log_make.txt](https://github.com/fagg/matlab-zmq/files/479929/log_make.txt)
[log_make_test.txt](https://github.com/fagg/matlab-zmq/files/479930/log_make_test.txt)

Here the config_win.m file. It's the same config in config.m
[config_win.m.txt](https://github.com/fagg/matlab-zmq/files/479931/config_win.m.txt)

And here the compiler configuration with VS2013. But as said before also with Windows SDK 7.1 configured as compiler it doesn't work.
[log_config.txt](https://github.com/fagg/matlab-zmq/files/479928/log_config.txt)

Thanks for your efforts.

**Comment by abravalheri** [comment]
@Fetz93,

I could not make my installation of MATLAB (R2013a) to locate/work with Visual Studio 2013. The last version accepted here is VS2012, but for some reason MATLAB does not know how to locate it (or Microsoft changed the default location, and I don't know how to specify it manually).
Therefore I'm not sure how I can help you, since I cannot reproduce your environment here.

My current configuration for compiler is `Microsoft Software Development Kit (SDK) 7.1 in C:\Program Files (x86)\Microsoft Visual Studio 10.0`. When you run `mex -setup` for SDK 7.1, do you get something similar?

Which are the extensions produced by  the `make` command inside `lib/+zmq/+core` folder? `*.mex`, `*.mexw32`,  `*.mex64`?

**Comment by Fetz93** [comment]
@abravalheri 

With the Microsoft SDK 7.1 is the same problem as said.
I can also reproduce the problem with MATLAB R2012b and Microsoft SDK 7.1. So this should be ok.

The extensions produced are  *.mexw64

**Comment by Fetz93** [comment]
I have now built the library as a dynamic release in Visual Studio and used this library instead of the installed one.
Now with the generated lib and dll I have 16 tests passed and only 2 failed.

**Comment by RobertKrajewski** [comment]
Using Vs 2013 and Matlab 2016a I also encountered the same issue as rshum19. Thankfully, removing the trailing backslash fixed the problem for me.

Edit: It was also necessary to add the zmq dlls to the windows path variable

**Comment by gongbudaizhe** [comment]
Just copy the zmq dlls to the directory of matlab-zmq fixed the problem
